### ISSUE TITLE
KDE unreadable font in firejail-ui

### ISSUE THREAD

**Issue by dalechyn** [netblue30/firetools#43] opened 2019-06-29 21:39 UTC
Font's are not working correct on black-themed KDE:
![image](https://user-images.githubusercontent.com/35642018/60389713-7eeed580-9acf-11e9-9a46-93915d14f41b.png)

**Comment by rusty-snake** [comment] 2019-06-30 09:33
Duplicate of #38

**Comment by startx2017** [comment] 2019-07-06 13:43
Fix in git:  https://github.com/netblue30/firetools/commit/2a8f6a238ca4a93fb67abc24106f903fd9a4827f

**Closed as completed by startx2017** 2019-07-06 13:43 UTC
